name: shoesly
description: "A shoes ecomerence flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.1
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.5
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/core/assets/images/

